---
- name: Group hosts by  distribution
  group_by: key={{ ansible_distribution }}
  tags: common

- name: Group hosts by distribution-version
  group_by: key={{ ansible_distribution }}-{{ ansible_distribution_major_version|int }}
  tags: common
