---
- name: Restart rails
  become: yes
  become_user: erratatool
  file: path={{ rails_root }}/tmp/restart.txt state=touch

- name: Restart other services
  become: yes
  service: name={{ item }} state=restarted
  with_items: services
